.\" The ROme OpTimistic Simulator (ROOT-Sim) Manual
.\" written by the High Performance and Dependable Computing Systems
.\" Sapienza, University of Rome
.\" http://www.dis.uniroma1.it/~hpdcs
.\"
.\" May 09 2011, Alessandro Pellegrini
.\" 	First version of the manpages

.TH rootsim 3 2011-05-09 "The ROme OpTimistic Simulator"

.SH NAME
rootsim - ROOT-Sim's interactive shell.

.SH SYNOPSIS

.B rootsim

.SH DESCRIPTION

Descrizione dell'uso di ROOT-Sim con la shell

.SH RULE SCRIPT

Descrizione dell'uso della shell con un file di configurazione (stile gnuplot)

.SH COMMAND LINE USAGE

E qui la descrizione di come usare rootsim invocando da riga di comando.


.SH SEE ALSO
.BR ROOT-Sim (7),
.BR ProcessEvent (3),
.BR OnGVT (3),
.BR ScheduleNewEvent (3),
.BR SetState (3),
.BR ROOT-Sim.h (3)

.SH COPYRIGHT
ROOT-Sim is developed by the
.I High Performance and Dependable Computing Systems
(HPDCS) Group at
.I Sapienza, University of Rome,
all the copyrights belong to the Group, and the software is released under GPL-3 License.


For further details, see the page http://www.dis.uniroma1.it/~hpdcs/ROOT-Sim/
