#define EVT_INSTRUCTIONS_RETIRED 			0
#define EVT_UNHALTED_CORE_CYCLES 			1
#define EVT_UNHALTED_REFERENCE_CYCLES 		2
#define EVT_BR_INST_RETIRED_ALL_BRANCHES	3
#define EVT_MEM_INST_RETIRED_ALL_LOADS		4
#define EVT_MEM_INST_RETIRED_ALL_STORES		5
#define EVT_MEM_LOAD_RETIRED_L3_HIT			6
 