#define EVENT(e, u) ((u << 8) | e)

/* Architectural events */
#define EVT_INSTRUCTIONS_RETIRED 		EVENT(0xC0, 0x00)


#define EVT_UNHALTED_CORE_CYCLES 		EVENT(0x3C, 0x00)
#define EVT_UNHALTED_REFERENCE_CYCLES 		EVENT(0x3C, 0x10)

#define EVT_BR_INST_RETIRED_ALL_BRANCHES	EVENT(0xC4, 0x00)


#define EVT_MEM_INST_RETIRED_ALL_LOADS		EVENT(0xD0, 0x81)
#define EVT_MEM_INST_RETIRED_ALL_STORES		EVENT(0xD0, 0x82)

#define EVT_MEM_LOAD_RETIRED_L3_HIT		EVENT(0xD1, 0x20)




// 04H 01H MEM_UOPS_RETIRED.L1_MISS_LOADS 
// 04H 02H MEM_UOPS_RETIRED.L2_HIT_LOADS 
// 04H 04H MEM_UOPS_RETIRED.L2_MISS_LOADS 
// 04H 08H MEM_UOPS_RETIRED.DTLB_MISS_LOADS 
// 04H 10H MEM_UOPS_RETIRED.UTLB_MISS 
// 04H 20H MEM_UOPS_RETIRED.HITM 
// 04H 40H MEM_UOPS_RETIRED.ALL_LOADS 
// 04H 80H MEM_UOP_RETIRED.ALL_STORES 